import prices from './marketPricesData.json';
import type { CropId } from './diseaseClasses';

// Real WFP food price data (via HDX), regenerated by
// model/scripts/build_price_reference.py. This is the direct answer to the
// problem named in the hackathon's own scenario: Noor "sells her parchment
// to whichever middleman drives up the valley, at whatever price he
// names" — because she has no independent reference. This is that
// reference. Not a live feed: a monthly snapshot, refreshed by re-running
// the generator script.
export interface PricePoint {
  date: string;
  avg_usd_per_kg: number;
  n_markets: number;
}

export interface MarketPrice {
  commodity: string;
  reference_country: string;
  unit: string;
  latest_date: string;
  latest_avg_usd_per_kg: number;
  latest_n_markets: number;
  trend: PricePoint[];
  source: string;
  note: string;
}

export const MARKET_PRICES = prices as unknown as Record<CropId, MarketPrice>;

export function marketPriceFor(cropId: CropId): MarketPrice | undefined {
  return MARKET_PRICES[cropId];
}

export function priceChangePercent(price: MarketPrice): number {
  const first = price.trend[0]?.avg_usd_per_kg ?? price.latest_avg_usd_per_kg;
  return ((price.latest_avg_usd_per_kg - first) / first) * 100;
}
